version: "3.2"

services:
  loggy-server:
    build:
      context: .
    volumes:
    - ./:/app
    ports:
    - 8080:8080

  mongodb:
    image: mongo:4.2.12
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
    - 27017:27017

volumes:
  mongodb_data:
